# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a82912a4bc457521d09ad53743947f30faa29c5404a848081066f49f5c45ac35f0fac0760c2843732c259a800c916699ea03fefaf93d58f1275592f5228fcbe1

test:
  secret_key_base: cb8c54def841a5072d7feeabd1966dff3f8bd072e682dae61dd020ee657d95b73d2cb7cffc6d7535824c6bdf9ce62e8fa9bc8b8716a040bc68c663b07b1ba875

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
