# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

State.create(state_name: 'Alabama', state_id: 1)
State.create(state_name: 'Alaska', state_id: 2)
State.create(state_name: 'Arizona', state_id: 3)
State.create(state_name: 'Arkansas', state_id: 4)
State.create(state_name: 'California', state_id: 5)
State.create(state_name: 'Colorado', state_id: 6)
State.create(state_name: 'Connecticut', state_id: 7)
State.create(state_name: 'Delaware', state_id: 8)
State.create(state_name: 'Florida', state_id: 9)
State.create(state_name: 'Georgia', state_id: 10)
State.create(state_name: 'Hawaii', state_id: 11)
State.create(state_name: 'Idaho', state_id: 12)
State.create(state_name: 'Illinois', state_id: 13)
State.create(state_name: 'Indiana', state_id: 14)
State.create(state_name: 'Iowa', state_id: 15)
State.create(state_name: 'Kansas', state_id: 16)
State.create(state_name: 'Kentucky', state_id: 17)
State.create(state_name: 'Louisiana', state_id: 18)
State.create(state_name: 'Maine', state_id: 19)
State.create(state_name: 'Maryland', state_id: 20)
State.create(state_name: 'Massachusetts', state_id: 21)
State.create(state_name: 'Michigan', state_id: 22)
State.create(state_name: 'Minnesota', state_id: 23)
State.create(state_name: 'Mississippi', state_id: 24)
State.create(state_name: 'Missouri', state_id: 25)
State.create(state_name: 'Montana', state_id: 26)
State.create(state_name: 'Nebraska', state_id: 27)
State.create(state_name: 'Nevada', state_id: 28)
State.create(state_name: 'New Hampshire', state_id: 29)
State.create(state_name: 'New Jersey', state_id: 30)
State.create(state_name: 'New Mexico', state_id: 31)
State.create(state_name: 'New York', state_id: 32)
State.create(state_name: 'North Carolina', state_id: 33)
State.create(state_name: 'North Dakota', state_id: 34)
State.create(state_name: 'Ohio', state_id: 35)
State.create(state_name: 'Oklahoma', state_id: 36)
State.create(state_name: 'Oregon', state_id: 37)
State.create(state_name: 'Pennsylvania', state_id: 38)
State.create(state_name: 'Rhode Island', state_id: 39)
State.create(state_name: 'South Carolina', state_id: 40)
State.create(state_name: 'South Dakota', state_id: 41)
State.create(state_name: 'Tennessee', state_id: 42)
State.create(state_name: 'Texas', state_id: 43)
State.create(state_name: 'Utah', state_id: 44)
State.create(state_name: 'Vermont', state_id: 45)
State.create(state_name: 'Virginia', state_id: 46)
State.create(state_name: 'Washington', state_id: 47)
State.create(state_name: 'West Virginia', state_id: 48)
State.create(state_name: 'Wisconsin', state_id: 49)
State.create(state_name: 'Wyoming', state_id: 50)
